\documentclass[10pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{amssymb, amsmath, amsthm, verbatim, layout, setspace, graphicx, float, geometry}
\usepackage{booktabs}

\newcommand{\textnote}[1]{\textbf{\textit{#1}}}
\newcommand{\code}[1]{\textbf{\textit{#1}}}
\newcommand{\grad}{\nabla}

% ------ layout ------
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\title{Linear Regression}
\author{Jeremy Oldfather}
\maketitle



\section*{Review}

\subsection*{What is linear regression?}

Start with a line.

\begin{align}
y &= mx + b \label{line}
\end{align}


We know how this appears visually. The line crosses the y-axis at the height of $b$ (intercept) and for each unit we move left or right, we move up or down by $m$ (slope) units. For example, with $b=10$ and $m=.7$, we get the following line:

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{b}\hlkwb{<-}\hlnum{10}
\hlstd{m}\hlkwb{<-}\hlnum{.7}
\hlstd{x}\hlkwb{<-}\hlnum{0}\hlopt{:}\hlnum{50}
\hlstd{y}\hlkwb{<-}\hlstd{m}\hlopt{*}\hlstd{x} \hlopt{+} \hlstd{b}
\hlkwd{qplot}\hlstd{(x,y,}\hlkwc{geom}\hlstd{=}\hlstr{"line"}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/simple_line-1} 

}



\end{knitrout}

Since the line has two parameters, $m$ and $b$, we could take any {\bf two} distinct points, draw a line between them, and solve for the parameters. If we only have {\bf one} point, we could draw infinitely many lines through the point.

Let's take this idea to some data. I have some data on the sales of DC properties. We can conceptualize each property as a point. Here is the \code{sale\_price} and \code{living\_sqft} of the first two properties. 

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# see: https://github.com/theoldfather/DC_Properties}
\hlstd{sales}\hlkwb{<-}\hlkwd{read_csv}\hlstd{(}\hlstr{"~/Projects/DC_Properties/data/sales_clean.csv"}\hlstd{)}
\hlstd{features}\hlkwb{<-}\hlkwd{read_csv}\hlstd{(}\hlstr{"~/Projects/DC_Properties/data/features_clean.csv"}\hlstd{)}
\hlstd{details}\hlkwb{<-}\hlkwd{read_csv}\hlstd{(}\hlstr{"~/Projects/DC_Properties/data/details_clean.csv"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{d}\hlkwb{<-}\hlstd{sales} \hlopt{%>%}
  \hlkwd{filter}\hlstd{(sale_price}\hlopt{>}\hlnum{0}\hlstd{)} \hlopt{%>%}
  \hlkwd{left_join}\hlstd{(features,}\hlkwc{by}\hlstd{=}\hlstr{"ssl"}\hlstd{)} \hlopt{%>%}
  \hlkwd{filter}\hlstd{(}\hlopt{!}\hlkwd{is.na}\hlstd{(living_sqft)} \hlopt{&} \hlstd{living_sqft}\hlopt{>}\hlnum{0}\hlstd{)} \hlopt{%>%}
  \hlkwd{select}\hlstd{(sale_price,living_sqft)}
\hlkwd{head}\hlstd{(d,}\hlnum{2}\hlstd{)} \hlopt{%>%} \hlkwd{data.frame}\hlstd{()}
\end{alltt}
\begin{verbatim}
##   sale_price living_sqft
## 1     200000        1505
## 2     650000        1281
\end{verbatim}
\end{kframe}
\end{knitrout}

Plotting these two points, we get the following scatterplot.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{ggplot}\hlstd{(d[}\hlnum{1}\hlopt{:}\hlnum{2}\hlstd{,],}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=living_sqft,}\hlkwc{y}\hlstd{=sale_price))} \hlopt{+} \hlkwd{geom_point}\hlstd{()}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/plot2-1} 

}



\end{knitrout}

We could draw a segment between the lines by changing \code{geom\_point()} to \code{geom\_line()}, but let's do it by finding the slope and intercept, and then plotting the line through the points.

If we subscript equation \ref{line} with $i$ to represent each observation, we can write it in a condensed notation as

\begin{align}
y_i &= m x_i + b \label{line_general}
\end{align}

and then expand it for $i \in \{1,2\}$.

\begin{align}
y_1 &= m x_1 + b \\
y_2 &= m x_2 + b
\end{align}

Solving for $m$ and $b$ we get

\begin{align}
m = \frac{y_2 - y_1}{x_2-x_1} \label{solution_slope} \\
b = y_1 - mx_1 \label{solution_intercept}
\end{align}

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{fit_line}\hlkwb{<-}\hlkwa{function}\hlstd{(}\hlkwc{y}\hlstd{,}\hlkwc{x}\hlstd{)\{}
  \hlstd{m} \hlkwb{<-} \hlstd{(y[}\hlnum{2}\hlstd{]}\hlopt{-}\hlstd{y[}\hlnum{1}\hlstd{])}\hlopt{/}\hlstd{(x[}\hlnum{2}\hlstd{]}\hlopt{-}\hlstd{x[}\hlnum{1}\hlstd{])}
  \hlstd{b} \hlkwb{<-} \hlstd{y[}\hlnum{1}\hlstd{]} \hlopt{-} \hlstd{m}\hlopt{*}\hlstd{x[}\hlnum{1}\hlstd{]}
  \hlkwd{return}\hlstd{(}\hlkwd{c}\hlstd{(b,m))}
\hlstd{\}}
\hlstd{beta}\hlkwb{<-}\hlkwd{fit_line}\hlstd{(d}\hlopt{$}\hlstd{sale_price[}\hlnum{1}\hlopt{:}\hlnum{2}\hlstd{],d}\hlopt{$}\hlstd{living_sqft[}\hlnum{1}\hlopt{:}\hlnum{2}\hlstd{])}
\hlkwd{ggplot}\hlstd{(d[}\hlnum{1}\hlopt{:}\hlnum{2}\hlstd{,],}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=living_sqft,}\hlkwc{y}\hlstd{=sale_price))} \hlopt{+}
  \hlkwd{geom_point}\hlstd{()} \hlopt{+} \hlkwd{geom_abline}\hlstd{(}\hlkwc{intercept}\hlstd{=beta[}\hlnum{1}\hlstd{],}\hlkwc{slope}\hlstd{=beta[}\hlnum{2}\hlstd{])}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/fit_line-1} 

}



\end{knitrout}

Do you believe this is an accurate model of the relationship between sales price and the living area of a home? $b=\ensuremath{3.2234375\times 10^{6}}$ implies that a house with no space would be worth \$3 million. And $m=\ensuremath{-2008.9285714}$ implies that increasing the living area of a home by 1 sqft would decrease its values by \$2,008. 

Thankfully, we have data on more than two homes. But what does it mean to draw a line through {\bf more than two} points? We know our model above is very bad---so not every point will fall on the same line.

Here is the rest of our data plotted on log-log scale (we will talk about log-log scale later).

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{ggplot}\hlstd{(d,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=living_sqft,}\hlkwc{y}\hlstd{=sale_price))} \hlopt{+}
  \hlkwd{geom_point}\hlstd{(}\hlkwc{alpha}\hlstd{=}\hlnum{.1}\hlstd{)} \hlopt{+} \hlkwd{scale_y_log10}\hlstd{()} \hlopt{+} \hlkwd{scale_x_log10}\hlstd{()}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/scatter_all-1} 

}



\end{knitrout}

This scatterplot seems promising--it visually re-enforces our beliefs that people place more value on larger homes. But we still want to quantify these beliefs to inform decision about buying, selling, making home improvements, etc.

Even though there is not a single line that can pass through each point, we can still find an "average line" that best-fits the data. This is the essence of regression.

\subsection*{Simple Linear Regression}

Let's expand our general formula for a line above (Equation \ref{line_general}) to express the fact that our line does not fit exactly, but rather has some slack distance between it and each point. 

\begin{align}
y_i &= mx_i + b + \epsilon_i
\end{align}

The slack or {\bf residual } term, $\epsilon_i$, also gets a subscript $i$ because we cannot assume that the line will be the same distance (vertically) from every point. Or in other words, our model will explain some home prices better than others. 

Let's also formalize the notation a bit more and replace $b$ with $\beta_0$ and $m$ with $\beta_1$. Many papers use beta ($\beta$) to represent the parameters of the model, but sometimes you will also find the intercept represented as alpha ($\alpha$). This is simply different notation and has the same meaning. 

\begin{align}
y_i &= \beta_0 + \beta_1 x_i + \epsilon_i
\end{align}

Next, we need some way of defining what it means to be the line of best-fit. What we want conceptually is the model that explains our data most accurately, and on the flip-side, the model that is the least inaccurate. Let's use the latter conceptualization and rewrite the equation above in terms of $\epsilon_i$

\begin{align}
\epsilon_i &=  ( y_i -  (\beta_0 + \beta_1 x_i) )
\end{align}

But minimizing a single residual is not helpful. Residuals can be negative, so the further we shift the fitted line above our points, the more and more negative each residual will become. We could keep shifting the line higher and higher and always produce a more negative residual. What if we square the residual---$\epsilon^2_i$? Now a point that is 6 units below the fitted line will be as equally bad as a point 6 units above the line.  

\begin{align}
\epsilon^2_i &=  ( y_i -  (\beta_0 + \beta_1 x_i) )^2
\end{align}

And we want to consider the value of all the squared residuals as once so that each point plays a role is how our line is fit. Summing over the squared residuals leads to the following formulation:

\begin{align}
\sum_i \epsilon^2_i &=  \sum_i ( y_i -  (\beta_0 + \beta_1 x_i) )^2
\end{align}

This is the intuition behind the loss function (the function to be minimized) in simple linear regression called the \textbf{Sum of Squared Residuals (SSR)}.

\begin{align}
SSR(\beta_0, \beta_1) &= \sum_i ( y_i -  (\beta_0 + \beta_1 x_i) )^2
\end{align}

By minimizing the SSR, we can find unique solutions for the coefficients $\beta_0$ and $\beta_1$. One way to do this is by taking the derivative of $SSR(\beta_0, \beta_1)$ with respect to each $\beta$, setting the derivatives equal to zero, and then solving for the coefficients. The following solutions are exactly analogous to the solutions for the intercept and slope of the line in Equations (\ref{solution_intercept}) and (\ref{solution_slope}).

\begin{align}
\beta_1 &= \frac{ \sum_i y_i x_i - \frac{\sum_i y_i \sum_i x_i}{n} }{ \sum_i x_i^2 - \frac{(\sum_i x_i)^2}{n} } \\
\beta_0 &=  \sum_i y_i - \beta_1 \sum_i x_i 
\end{align}

This might look messy at first, but notice there are really only 4 statistics we need to compute: 

\begin{align}
\sum_i & y_i x_i \\
\sum_i & y_i \\
\sum_i & x_i \\
\sum_i & x_i^2
\end{align}

Using this idea, let's write a function to estimate the betas in R. 

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{fit_simple_lm}\hlkwb{<-}\hlkwa{function}\hlstd{(}\hlkwc{y}\hlstd{,}\hlkwc{x}\hlstd{)\{}
  \hlstd{n}\hlkwb{<-}\hlkwd{length}\hlstd{(y)}
  \hlstd{syx}\hlkwb{<-}\hlkwd{sum}\hlstd{(y}\hlopt{*}\hlstd{x)}
  \hlstd{sy}\hlkwb{<-}\hlkwd{sum}\hlstd{(y)}
  \hlstd{sx}\hlkwb{<-}\hlkwd{sum}\hlstd{(x)}
  \hlstd{sxx}\hlkwb{<-}\hlkwd{sum}\hlstd{(x}\hlopt{^}\hlnum{2}\hlstd{)}
  \hlstd{b1}\hlkwb{<-} \hlstd{(syx} \hlopt{-} \hlstd{sy}\hlopt{*}\hlstd{sx}\hlopt{/}\hlstd{n)}\hlopt{/}\hlstd{(sxx} \hlopt{-} \hlstd{sx}\hlopt{^}\hlnum{2}\hlopt{/}\hlstd{n)}
  \hlstd{b0}\hlkwb{<-} \hlstd{(sy} \hlopt{-} \hlstd{b1}\hlopt{*}\hlstd{sx)}\hlopt{/}\hlstd{n}
  \hlkwd{return}\hlstd{(}\hlkwd{c}\hlstd{(b0,b1))}
\hlstd{\}}
\end{alltt}
\end{kframe}
\end{knitrout}

Now we can use our function to estimate the betas--the coefficients of our simple linear model.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# find our betas}
\hlstd{beta}\hlkwb{<-}\hlkwd{fit_simple_lm}\hlstd{(}\hlkwc{y}\hlstd{=d}\hlopt{$}\hlstd{sale_price,}\hlkwc{x}\hlstd{=d}\hlopt{$}\hlstd{living_sqft)}
\hlcom{# use betas to create a data frame of fitted sales prices }
\hlstd{E}\hlkwb{<-}\hlkwd{data.frame}\hlstd{(}\hlkwc{sale_price}\hlstd{=beta[}\hlnum{1}\hlstd{]}\hlopt{+}\hlstd{beta[}\hlnum{2}\hlstd{]}\hlopt{*}\hlstd{d}\hlopt{$}\hlstd{living_sqft,}
                   \hlkwc{living_sqft}\hlstd{=d}\hlopt{$}\hlstd{living_sqft)}
\hlcom{# plot our data and the fitted line}
\hlkwd{ggplot}\hlstd{(d,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=living_sqft,}\hlkwc{y}\hlstd{=sale_price))} \hlopt{+}
  \hlkwd{geom_point}\hlstd{(}\hlkwc{alpha}\hlstd{=}\hlnum{.1}\hlstd{)} \hlopt{+}
  \hlkwd{geom_line}\hlstd{(}\hlkwc{data}\hlstd{=E,}\hlkwc{colour}\hlstd{=}\hlstr{"orange"}\hlstd{)} \hlopt{+}
  \hlkwd{scale_y_log10}\hlstd{()} \hlopt{+} \hlkwd{scale_x_log10}\hlstd{()}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/use_fit_simple_lm-1} 

}



\end{knitrout}

The fitted line is beginning to look more intuitive and it is certainly a better model than the one constructed from two points. But why is it curved? I thought we fitted a "line"?

The answer is that the order in which we apply convex/concave functions to our data and fitted model matters! We can get this right by referencing \textbf{Jensen's Inequality}, which states that when we apply a concave function (think of a hill that could "cave" in) to an expected value, its output will always be greater than or equal to the expected values of the same function applied to the input. If $f(x)$ is the concave function, the inequality is:

\begin{align}
f(E(x)) & \ge E(f(x))
\end{align}

In our case, $log(x)$ is the concave function and $E(x)$ is our fitted line, $\hat{y}_i = \beta_0 + \beta_1 x_i$. We can visualize the difference this order of operations makes by plotting both alternatives. The \textbf{orange} line is what we plotted before, $log(E(\beta_0 + \beta_1 x_i))$, and the \textbf{blue} one is the model fitted on the log data, $E(log(\beta_0 + \beta_1 x_i))$.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# log scale both y and x manually}
\hlstd{logd} \hlkwb{<-} \hlstd{d} \hlopt{%>%}
  \hlkwd{mutate}\hlstd{(}\hlkwc{log_sale_price}\hlstd{=}\hlkwd{log}\hlstd{(sale_price),}
         \hlkwc{log_living_sqft}\hlstd{=}\hlkwd{log}\hlstd{(living_sqft))}
\hlcom{# estimate betas again based on log-log model}
\hlstd{beta}\hlkwb{<-}\hlkwd{fit_simple_lm}\hlstd{(}\hlkwc{y}\hlstd{=logd}\hlopt{$}\hlstd{log_sale_price,}\hlkwc{x}\hlstd{=logd}\hlopt{$}\hlstd{log_living_sqft)}
\hlcom{# E(log(x))}
\hlstd{E_log}\hlkwb{<-}\hlkwd{data.frame}\hlstd{(}\hlkwc{log_sale_price}\hlstd{=beta[}\hlnum{1}\hlstd{]}\hlopt{+}\hlstd{beta[}\hlnum{2}\hlstd{]}\hlopt{*}\hlstd{logd}\hlopt{$}\hlstd{log_living_sqft,}
                   \hlkwc{log_living_sqft}\hlstd{=logd}\hlopt{$}\hlstd{log_living_sqft)}
\hlcom{# log(E(x))}
\hlstd{log_E}\hlkwb{<-}\hlstd{E} \hlopt{%>%} \hlkwd{mutate}\hlstd{(}\hlkwc{log_sale_price} \hlstd{=} \hlkwd{log}\hlstd{(sale_price),}
                    \hlkwc{log_living_sqft} \hlstd{=} \hlkwd{log}\hlstd{(living_sqft))}
\hlcom{# plot the log-log data manually (no scale_y_log10() or scale_x_log10() )}
\hlkwd{ggplot}\hlstd{(logd,}\hlkwd{aes}\hlstd{(}\hlkwc{x}\hlstd{=log_living_sqft,}\hlkwc{y}\hlstd{=log_sale_price))} \hlopt{+}
  \hlkwd{geom_point}\hlstd{(}\hlkwc{alpha}\hlstd{=}\hlnum{.1}\hlstd{)} \hlopt{+}
  \hlkwd{geom_line}\hlstd{(}\hlkwc{data}\hlstd{=log_E,}\hlkwc{colour}\hlstd{=}\hlstr{"orange"}\hlstd{)} \hlopt{+}
  \hlkwd{geom_line}\hlstd{(}\hlkwc{data}\hlstd{=E_log,}\hlkwc{colour}\hlstd{=}\hlstr{"blue"}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/fit_simple_lm_log-1} 

}


\begin{kframe}\begin{alltt}
\hlstd{beta}
\end{alltt}
\begin{verbatim}
## [1] 7.8751859 0.7063513
\end{verbatim}
\end{kframe}
\end{knitrout}

\subsection*{Interpretting a Linear Regression}

Now that we finally have the fitted line that we expected to see (the blue one), let's step back and think about how we should interpret the coefficients that parameterize it: $\beta_1 =$ 0.7063513 and $\beta_0 =$ 7.8751859.

\subsubsection*{level-level}

With a level-level model, we have the raw levels of variables on each side of the regression.

$$ y_i = \beta_0 + \beta_1 x_i + \epsilon_i $$

Since this model has the form of a line, we can interpret $\beta_1$ as the slope, $\Delta y / \Delta x$. To prove this to ourselves, we only need to take the derivative of the model with respect to $x$.

\begin{align}
\frac{dy}{dx} &=\beta_1 \\
\beta_1 &= \frac{dy}{dx}
\end{align}

So we can interpret $\beta1$ as the {\bf marginal effect} since a 1 unit increase in $x$ leads to a $\beta_1$ unit change in $y$.

\subsubsection*{log-level}

A log-level model is not as intuitive, but we can apply the same analysis to arrive at an interpretation.

\begin{align}
log(y_i) &=  \beta_0 + \beta_1 x_i + \epsilon_i \\
y_i &= e^{\beta_0 + \beta_1 x_i + \epsilon_i}
\end{align}

Taking the derivative with respect to $x$:

\begin{align}
\frac{dy}{dx} &= \beta_1 e^{\beta_0 + \beta_1 x_i + \epsilon_i} \\
 &= \beta_1 y 
\end{align}

Solving for $\beta_1$:

\begin{align}
 \beta_1 &= \frac{dy}{dx} \frac{1}{y}
\end{align}

The \textbf{marginal effect}, $dy / dx = \beta_1 y$, implies that a change in $x$ will impact $y$ differently depending on the level of $y$. For instance, if $\beta_1 = .001$, and the current value of my home is \$100,000 and I decide to build an extension that increases its area by 200 sqft., then I would expect its change in value from the improvement to be $$.001 \cdot 100,000 \cdot 200 = 20,000$$ But if my home is currently worth \$200,000, then I expect the improvement to increase it by $$.001 \cdot 200,000 \cdot 200 = 40,000$$

\subsubsection*{log-log}

For a log-log model (our example for this lession), we can apply the same analysis as the previous two models. Starting from the model equation:

\begin{align}
log(y_i) &=  \beta_0 + \beta_1 log(x_i) + \epsilon_i \\
y_i &= e^{\beta_0 + \beta_1 log(x_i) + \epsilon_i}
\end{align}

Take the derivative with respect to $x$:

\begin{align}
\frac{dy}{dx} &= \beta_1 e^{\beta_0 + \beta_1 x_i + \epsilon_i} \cdot \frac{1}{x_i} \\
 &= \beta_1 \frac{y}{x} 
\end{align}

Solving for $\beta_1$:

\begin{align}
 \beta_1 &= \frac{dy}{dx} \frac{x}{y}
\end{align}

The \textbf{marginal effect}, $dy / dx = \beta_1 y / x$, implies that a change in $x$ will impact $y$ differently depending on the level of $y$ relative to $x$. For instance, let's say $\beta_1 = .001$, the current value of my home is \$100,000, and its living area is 1000 sqft. Now if I decide to build an extension that increases its area by 200 sqft., then I would expect its change in value from the improvement to be 

$$.001 \cdot 100,000 / 1000 \cdot 200 = 20$$ 

But if my home is currently worth \$200,000, then I expect the improvement to increase its value by 

$$.001 \cdot 200,000/1000 \cdot 200 = 40$$

Since the model we have been using is in log-log form, let's plug its coefficient for living area into my hypothetical home renovation scenerio.

$$0.7063513 \cdot 200,000/1000 \cdot 200 = 14,127.03$$


\subsection*{Simple Linear Regression in R }

Thankfully, R has some built-in regression tools--we don't need to write our own each time we want to fit a model. All we need is a data frame and model formula. First, let's create the data frame.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# subset some data for a regression}
\hlcom{# and make sure both sale_price and living_sqft are log-scaled}
\hlstd{data.model}\hlkwb{<-}\hlstd{sales} \hlopt{%>%}
  \hlkwd{filter}\hlstd{(sale_price}\hlopt{>}\hlnum{0}\hlstd{)} \hlopt{%>%}
  \hlkwd{left_join}\hlstd{(features,}\hlkwc{by}\hlstd{=}\hlstr{"ssl"}\hlstd{)} \hlopt{%>%}
  \hlkwd{left_join}\hlstd{(}\hlkwd{select}\hlstd{(details,}\hlopt{-}\hlstd{sale_price,}\hlopt{-}\hlstd{neighborhood),}\hlkwc{by}\hlstd{=}\hlstr{"ssl"}\hlstd{)} \hlopt{%>%}
  \hlkwd{filter}\hlstd{(}\hlopt{!}\hlkwd{is.na}\hlstd{(living_sqft)} \hlopt{&} \hlstd{living_sqft}\hlopt{>}\hlnum{0}\hlstd{)} \hlopt{%>%}
  \hlkwd{mutate}\hlstd{(}\hlkwc{log_sale_price}\hlstd{=}\hlkwd{log}\hlstd{(sale_price),}
         \hlkwc{log_living_sqft}\hlstd{=}\hlkwd{log}\hlstd{(living_sqft))}
\end{alltt}
\end{kframe}
\end{knitrout}

Next, let's write our model as an R formula. Our model is:

$$ log(sale\_price_i) = \beta_0 + \beta_1 log(living\_sqft_i) + \epsilon_i$$

In R, we simply write

$$ log\_sale\_price \sim log\_living\_sqft $$

Then we give both pieces of information to {\bf lm()}, R's linear model function.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{lm}\hlstd{(log_sale_price} \hlopt{~} \hlstd{log_living_sqft,} \hlkwc{data}\hlstd{=data.model)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## lm(formula = log_sale_price ~ log_living_sqft, data = data.model)
## 
## Coefficients:
##     (Intercept)  log_living_sqft  
##          7.8752           0.7064
\end{verbatim}
\end{kframe}
\end{knitrout}

Notice that in the formula, we do not need to specify the implicit {\bf 1} for $\beta_0$. R assumes we want an intercept by default. But we could specify this if we really want a reminder that it is there.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{lm}\hlstd{(log_sale_price} \hlopt{~} \hlnum{1} \hlopt{+} \hlstd{log_living_sqft,} \hlkwc{data}\hlstd{=data.model)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## lm(formula = log_sale_price ~ 1 + log_living_sqft, data = data.model)
## 
## Coefficients:
##     (Intercept)  log_living_sqft  
##          7.8752           0.7064
\end{verbatim}
\end{kframe}
\end{knitrout}

And if we wanted a model without an intercept, we could simply subtract {\bf 1} from the formula. This forces our fitted line to be drawn through the origin.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{lm}\hlstd{(log_sale_price} \hlopt{~ -}\hlnum{1} \hlopt{+} \hlstd{log_living_sqft,} \hlkwc{data}\hlstd{=data.model)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## lm(formula = log_sale_price ~ -1 + log_living_sqft, data = data.model)
## 
## Coefficients:
## log_living_sqft  
##           1.813
\end{verbatim}
\end{kframe}
\end{knitrout}

\subsubsection*{Summarizing the regression}

The {\bf lm()} function returns an object that contains information about the regression that was run. If we do not assign the object to a variable, it will print the estimated coefficients to the screen. However, it is better to keep our results so we can summarize the regression in a paper, use the estimated coefficients for prediction, or analyze the residuals.

So let's run the previous regression and assign to the variable {\bf fit}.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{fit}\hlkwb{<-}\hlkwd{lm}\hlstd{(log_sale_price} \hlopt{~} \hlstd{log_living_sqft,} \hlkwc{data}\hlstd{=data.model)}
\end{alltt}
\end{kframe}
\end{knitrout}

The fitted lm object contains too much information to print here, but you can inspect it with the {\bf str()} function or by clicking on it in your Environment panel in Rstudio. The {\bf summary()} function will print a prettier version of the results to screen, similar to the output in Stata.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hlstd{(fit)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## lm(formula = log_sale_price ~ log_living_sqft, data = data.model)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.6189  -0.3601   0.1332   0.4313   6.5902 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     7.875186   0.033900   232.3   <2e-16 ***
## log_living_sqft 0.706351   0.004778   147.8   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7196 on 85295 degrees of freedom
## Multiple R-squared:  0.204,	Adjusted R-squared:  0.204 
## F-statistic: 2.186e+04 on 1 and 85295 DF,  p-value: < 2.2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}

And to get latex output of the table, we can use the { \bf stargazer } and print the results straight into our PDF.

\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(stargazer)} \hlcom{# you will need to install this package}
\hlkwd{stargazer}\hlstd{(fit,}\hlkwc{type}\hlstd{=}\hlstr{"latex"}\hlstd{,}\hlkwc{style}\hlstd{=}\hlstr{"qje"}\hlstd{)}
\end{alltt}
\end{kframe}
% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Tue, Oct 11, 2016 - 10:08:08 PM
\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
\\[-1.8ex] & log\_sale\_price \\ 
\hline \\[-1.8ex] 
 log\_living\_sqft & 0.706$^{***}$ \\ 
  & (0.005) \\ 
  & \\ 
 Constant & 7.875$^{***}$ \\ 
  & (0.034) \\ 
  & \\ 
\textit{N} & 85,297 \\ 
R$^{2}$ & 0.204 \\ 
Adjusted R$^{2}$ & 0.204 \\ 
Residual Std. Error & 0.720 (df = 85295) \\ 
F Statistic & 21,859.330$^{***}$ (df = 1; 85295) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Notes:} & \multicolumn{1}{r}{$^{***}$Significant at the 1 percent level.} \\ 
 & \multicolumn{1}{r}{$^{**}$Significant at the 5 percent level.} \\ 
 & \multicolumn{1}{r}{$^{*}$Significant at the 10 percent level.} \\ 
\end{tabular} 
\end{table} 



\subsubsection*{Extracting Model Components}

As we have seen, the fit object returned by {\bf lm()} contains the information about the regression that created the object. A benefit of holding on to the object is that we can extract components from the model and analyze them and/or compare them to those from other models.

\textbf{Coefficients ($\beta_k$).}  The betas of the model are stored as a named vector in the fit object and can be extracted by either explicitly referencing them,

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{fit}\hlopt{$}\hlstd{coefficients}
\end{alltt}
\begin{verbatim}
##     (Intercept) log_living_sqft 
##       7.8751859       0.7063513
\end{verbatim}
\end{kframe}
\end{knitrout}

or by applying the {\bf coef()} function to the object.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{coef}\hlstd{(fit)}
\end{alltt}
\begin{verbatim}
##     (Intercept) log_living_sqft 
##       7.8751859       0.7063513
\end{verbatim}
\end{kframe}
\end{knitrout}

\textbf{Fitted Values ($\hat{y}$).}  The fitted values, or simply $\hat{y}$, can be extracted by applying the {\bf fitted()} function to the object. 

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{rbind}\hlstd{(}\hlkwd{data.frame}\hlstd{(}\hlkwc{y}\hlstd{=data.model}\hlopt{$}\hlstd{log_sale_price,}\hlkwc{x}\hlstd{=data.model}\hlopt{$}\hlstd{log_living_sqft,}\hlkwc{label}\hlstd{=}\hlstr{"actual"}\hlstd{),}
      \hlkwd{data.frame}\hlstd{(}\hlkwc{y}\hlstd{=}\hlkwd{fitted}\hlstd{(fit),}\hlkwc{x}\hlstd{=data.model}\hlopt{$}\hlstd{log_living_sqft,}\hlkwc{label}\hlstd{=}\hlstr{"fitted"}\hlstd{)}
      \hlstd{)} \hlopt{%>%}
  \hlkwd{ggplot}\hlstd{(}\hlkwd{aes}\hlstd{(x,y,}\hlkwc{group}\hlstd{=label,}\hlkwc{colour}\hlstd{=label))} \hlopt{+} \hlkwd{geom_point}\hlstd{()}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/extract_fitted-1} 

}



\end{knitrout}

From our model, $\hat{y}_i = \beta_0 + \beta_1 x_i$ and $\epsilon_i = y_i - \hat{y}_i$. So in the scatterplot above, every $\hat{y}_i$ has a corresponding $y_i$ either directly above or below it. And the residual $\epsilon_i$ is the difference between them vertically. We can check this:

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{all.equal}\hlstd{(}\hlkwd{resid}\hlstd{(fit),(data.model}\hlopt{$}\hlstd{log_sale_price} \hlopt{-} \hlkwd{fitted}\hlstd{(fit)))}
\end{alltt}
\begin{verbatim}
## [1] TRUE
\end{verbatim}
\end{kframe}
\end{knitrout}

\textbf{Residuals ($\epsilon_i$).}  In you missed it in the last step, we can also extract the residuals, $\epsilon_i$, by applying the {\bf resid()} function to the fit object.

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{resid}\hlstd{(fit)} \hlopt{%>%} \hlkwd{summary}\hlstd{()}
\end{alltt}
\begin{verbatim}
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -13.6200  -0.3601   0.1332   0.0000   0.4313   6.5900
\end{verbatim}
\end{kframe}
\end{knitrout}

Residuals play a key role in our analysis of the goodness-of-fit of our model and will provide motivation for introducing {\bf multiple linear regression} in the next section.

\subsection*{Multiple Linear Regression}

\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{data.frame}\hlstd{(}\hlkwc{e}\hlstd{=}\hlkwd{resid}\hlstd{(fit),}\hlkwc{g}\hlstd{=data.model}\hlopt{$}\hlstd{neighborhood)} \hlopt{%>%}
  \hlkwd{filter}\hlstd{(g} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{"FOGGY BOTTOM"}\hlstd{,}\hlstr{"ANACOSTIA"}\hlstd{,}\hlstr{"LEDROIT PARK"}\hlstd{,}\hlstr{"TAKOMA"}\hlstd{,}\hlstr{"GEORGETOWN"}\hlstd{))} \hlopt{%>%}
  \hlkwd{ggplot}\hlstd{(}\hlkwd{aes}\hlstd{(}\hlkwc{y}\hlstd{=e,}\hlkwc{x}\hlstd{=g))} \hlopt{+} \hlkwd{geom_boxplot}\hlstd{()}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/boxplot_residuals-1} 

}



\end{knitrout}

\newpage

% ----- start appendices -----

\include{appendix}

\end{document}
